routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::group(['middleware' => 'auth.sso'], function () {
    Route::get('/', 'MessageController@index')->name('index');

    Route::group(['prefix' => 'inbox', 'as' => 'inbox.'], function () {
        Route::get('/', 'MessageController@showInbox')->name('index');
        Route::patch('action', 'MessageController@handleMessageAction')->name('action');

        Route::get('message/{message}', 'MessageController@showMessage')->name('detail');
    });

    Route::get('compose', 'MessageController@showComposeForm')->name('compose');
    Route::post('compose', 'MessageController@storeMessage')->name('compose.store');

    Route::get('sent-items/{id}', 'MessageController@showDetailSentItem')->name('sent-items.detail');
    Route::get('sent-items', 'MessageController@showSentItem')->name('sent-items');
});

resources/views/site/layouts/app.blade.php
<!DOCTYPE html>
<!--[if IE 8]>         <html class="ie8" lang="{{ app()->getLocale() }}"> <![endif]-->
<!--[if IE 9]>         <html class="ie9 gt-ie8" lang="{{ app()->getLocale() }}"> <![endif]-->
<!--[if gt IE 9]><!-->
<html class="gt-ie8 gt-ie9 not-ie" lang="{{ app()->getLocale() }}">
<!--<![endif]-->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <title>{{ trans_choice('layout.meta.title', !empty($title), ['appname' => config('app.name'), 'title' => $title ?? '']) }}</title>
    <!-- Open Sans font from Google CDN -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin"
        rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{{ asset('pixel-admin/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('pixel-admin/css/pixel-admin.min.css') }}">
    <link rel="stylesheet" href="{{ asset('pixel-admin/css/widgets.min.css') }}">
    <link rel="stylesheet" href="{{ asset('pixel-admin/css/pages.min.css') }}">
    <link rel="stylesheet" href="{{ asset('pixel-admin/css/themes.min.css') }}">
    <!--[if lt IE 9]>
        <script src="assets/javascripts/ie.min.js"></script>
    <![endif]-->
    @stack('styles')
</head>

<body class="theme-asphalt no-main-menu page-mail">
    <div id="main-wrapper">
        <div id="main-navbar" class="navbar navbar-inverse" role="navigation">
            @include('site.layouts.header')
        </div>

        {{-- <div id="main-menu" role="navigation">
            @include('site.layouts.sidebar')
        </div> --}}

        <div id="content-wrapper">
            @include('site.layouts.nav-messages')
            @yield('content')
        </div>
        @stack('html')
        <div id="main-menu-bg"></div>
    </div>
    <script src="{{ asset('pixel-admin/js/jquery.min.js') }}"></script>
    <script src="{{ asset('pixel-admin/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('pixel-admin/js/pixel-admin.min.js') }}"></script>
    <script src="{{ asset('js/bkm-mail.js') }}"></script>
    <script type="text/javascript">
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    </script>
    @stack('scripts')
    <script type="text/javascript">
        window.PixelAdmin.start(window.initPixel, {
            main_menu: {
                detect_active: false,
            }
        });
    </script>
</body>
</html>

resources/views/site/layouts/feedback.blade.php
@if (session('flash_messages'))
    @foreach (session('flash_messages') as $type => $messages)
        @php
            $_messages = !is_array($messages) ? [$messages] : $messages;
        @endphp
        @foreach ($_messages as $message)
            <div class="alert fade in alert-{{ config('site.flash-message.' . $type, 'info') }}">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4>{{ trans('messages.' . $type . '.title') }}</h4>
                {!! $message !!}
            </div>
        @endforeach
    @endforeach
@endif

resources/views/site/layouts/header.blade.php
<button type="button" id="main-menu-toggle"><i class="navbar-icon fa fa-bars icon"></i><span class="hide-menu-text">@lang('admin/layout.buttons.hide_menu')</span></button>
<div class="navbar-inner">
    <div class="navbar-header">
        <a href="{{ route('index') }}" class="navbar-brand">
            <div><img alt="{{ config('app.name') }}" src="{{ asset('assets/logo.png') }}"></div>
            {{ config('app.name') }}
        </a>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>
    </div>
    <div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
        <div>
            <ul class="nav navbar-nav"></ul>
            <div class="right clearfix">
                <ul class="nav navbar-nav pull-right right-navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown">
                            <span>{{ $broker_profile['name'] }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            {{-- <li>
                                <a href="#"><i class="dropdown-icon fa fa-cog"></i>&nbsp;&nbsp;Settings</a>
                            </li> --}}
                            <li class="divider"></li>
                            <li>
                                <a href="{{ $broker_logout_url }}"><i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Log Out</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

resources/views/site/layouts/nav-messages.blade.php
<div class="mail-nav">
    <div class="compose-btn">
        <a href="{{ route('compose') }}" class="btn btn-primary btn-labeled btn-block"><i class="btn-label fa fa-pencil-square-o"></i>@lang('layout.menu.message.child.compose')</a>
    </div>
    <div class="navigation">
        <ul class="sections">
            @if (Route::currentRouteName() == 'compose')
                <li class="mail-select-folder active"><a href="#">@lang('layout.menu.message.select_folder')</a></li>
            @endif
            <li class="{{ (!Request::has('type') && Request::segment(1)  == 'inbox') ? 'active' : '' }}">
                <a href="{{ route('inbox.index') }}">
                    <i class="m-nav-icon fa fa-inbox"></i>
                    @lang('layout.menu.message.child.inbox')
                    <span class="label pull-right">{{ $count_unread }}</span>
                </a>
            </li>
            <li class="{{ Route::currentRouteName() == 'sent-items' || Request::segment(1) == 'sent-items' ? 'active' : '' }}">
                <a href="{{ route('sent-items') }}">
                    <i class="m-nav-icon fa fa-envelope"></i>
                    @lang('layout.menu.message.child.sent')
                </a>
            </li>
            <li class="{{ (Request::has('type') && Request::input('type') == 'trash') ? 'active' : '' }}">
                <a href="{{ route('inbox.index', ['type' => 'trash']) }}">
                    <i class="m-nav-icon fa fa-trash-o"></i>
                    @lang('layout.menu.message.child.trash')
                </a>
            </li>
        </ul>
    </div>
</div>

resources/views/site/layouts/sidebar.blade.php
<div id="main-menu-inner">
    <ul class="navigation">
        <li class="{{ empty(Request::segment(1)) ? 'active' : '' }}">
            <a href="{{ route('index') }}">
                <i class="menu-icon fa fa-dashboard"></i>
                <span class="mm-text">@lang('layout.menu.dashboard.title')</span>
            </a>
        </li>
        <li class="mm-dropdown {{ in_array(Request::segment(1), ['inbox', 'compose', 'sent']) ? 'active open' : '' }}">
            <a href="#">
                <i class="menu-icon fa fa-envelope"></i>
                <span class="mm-text">@lang('layout.menu.message.title')</span>
            </a>
            <ul>
                <li class="{{ Request::segment(1) == 'inbox' ? 'active' : '' }}">
                    <a href="{{ route('inbox.index') }}">
                        <i class="menu-icon fa fa-inbox"></i>
                        <span class="mm-text">@lang('layout.menu.message.child.inbox')</span>
                    </a>
                </li>
                <li class="{{ Request::segment(1) == 'compose' ? 'active' : '' }}">
                    <a href="{{ route('compose') }}">
                        <i class="menu-icon fa fa-pencil-square-o"></i>
                        <span class="mm-text">@lang('layout.menu.message.child.compose')</span>
                    </a>
                </li>
                <li class="{{ Request::segment(1) == 'sent' ? 'active' : '' }}">
                    <a href="{{ route('sent-items') }}">
                        <i class="menu-icon fa fa-mail-forward"></i>
                        <span class="mm-text">@lang('layout.menu.message.child.sent')</span>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</div>