routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::group(['middleware' => 'auth.sso'], function () {
    Route::get('/', 'MessageController@index')->name('index');

    Route::group(['prefix' => 'inbox', 'as' => 'inbox.'], function () {
        Route::get('/', 'MessageController@showInbox')->name('index');
        Route::patch('action', 'MessageController@handleMessageAction')->name('action');

        Route::get('message/{message}', 'MessageController@showMessage')->name('detail');
    });

    Route::get('compose', 'MessageController@showComposeForm')->name('compose');
    Route::post('compose', 'MessageController@storeMessage')->name('compose.store');

    Route::get('sent-items/{id}', 'MessageController@showDetailSentItem')->name('sent-items.detail');
    Route::get('sent-items', 'MessageController@showSentItem')->name('sent-items');
});

app/Models/Message.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    protected $table = 'messages';

    protected $primaryKey = 'id';

    protected $fillable = [
        'user_id', 'sender_name', 'sender_email', 'subject', 'body',
    ];

    public function scopeAuthUser($query, $id)
    {
        return $query->where(function ($q) use ($id) {
            $q->where('user_id', $id)->orWhereRaw('BINARY `sender_email` = ?', [$id]);
        });
    }

    public function scopeJoinRecievers($query)
    {
        return $query->join(\DB::raw('(SELECT message_id, GROUP_CONCAT(email SEPARATOR ", ") as all_recievers FROM message_recievers GROUP BY message_id) as recievers'), 'messages.id', '=', 'recievers.message_id')->select('messages.*', 'recievers.all_recievers');
    }

    public function recievers()
    {
        return $this->hasMany(MessageReciever::class, 'message_id');
    }

    public function recieverEmails()
    {
        return $this->recievers()->where('email', '!=', 'auth_user_email');
    }
}

app/Models/MessageReciever.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;

class MessageReciever extends Model
{
    protected $table = 'message_recievers';

    protected $primaryKey = 'id';

    protected $perPage = 25;

    protected $fillable = [
        'message_id', 'email', 'status', 'sended_at',
    ];

    protected $dates = ['created_at', 'updated_at', 'sended_at'];

    const MSG_STATUS = [
        'fail' => 0,
        'sended' => 1,
        'pending' => 2,
        'read' => 3,
        'trash' => 4,
    ];

    /**
     * Get the Messages 
     *
     * @param array|string $search
     * @param string $type
     * @return array
     */
    public static function getMsgStatus($search = [], $type = "key")
    {
        $_status = ($type == "key") ? static::MSG_STATUS : array_flip(static::MSG_STATUS);

        if (!empty($search)) {
            if (is_string($search)) {
                $search = [$search];
            }

            $arr = [];
            foreach ($search as $key => $value) {
                if (array_key_exists($value, $_status)) {
                    $arr[] = $_status[$value];
                }
            }
            return array_values($arr);
        }
        return $_status;
    }

    public function scopeAuthUser($query, $id)
    {
        return $query->where(function($q) use($id){
            $q->where('user_id', $id)->orWhereRaw('BINARY `email` = ?', [$id]);
        });
    }

    public function scopeOnlyInbox($query)
    {
        return $this->scopeOnlyStatus($query, static::getMsgStatus([
            "sended", "read"
        ]));
    }

    public function scopeOnlyStatus($query, array $status = [])
    {
        if (!empty($status)) {
            $query->whereIn('status', $status);
        }
        return $query;
    }

    public function getMessageTypeDisplayAttribute()
    {
        $status = static::MSG_STATUS;
        if ($this->attributes['status'] == $status['sended'] || $this->attributes['status'] == $status['read']) {
            return 'Inbox';
        }
        return 'Trash';
    }

    public function getIsUnreadAttribute()
    {
        return $this->attributes['status'] === static::MSG_STATUS['sended'];
    }

    public function message()
    {
        return $this->belongsTo(Message::class, 'message_id', 'id');
    }
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use App\Libraries\Broker;
use App\Models\Message;
use App\Models\MessageReciever;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\ComposeMessage;
use Carbon\Carbon;

class MessageController extends Controller
{
    protected $hanldeAction = ['trash', 'destroy', 'unread'];

    public function index(Request $request)
    {
        return view('site.pages.dashboard');
    }

    public function showInbox(Request $request)
    {
        $messages = MessageReciever::authUser($request->auth_user['id'])->with([
                        'message:id,sender_name,sender_email,subject,body'
                    ])->orderBy('sended_at', 'DESC');

        $trash_action = 'trash';
        $params = [];

        if ($request->filled('type')) {
            $type = $request->input('type', 'inbox');

            if (!empty($types = explode(':', $type))) {
                $search = MessageReciever::getMsgStatus($types);
                $messages = $messages->onlyStatus($search);

                $trash_action = in_array(MessageReciever::MSG_STATUS['trash'], $search) ? 'destroy' : 'trash';
            } else {
                $messages = $messages->onlyInbox();
            }
            $params = ['type' => $type];
        }else{
            $messages = $messages->onlyInbox();
        }
        
        $data['params'] = $params;
        $data['trash_action'] = $trash_action;
        $data['inboxes'] = $messages->paginate()->appends($params);

        $data['title'] = trans('layout.menu.message.child.inbox');
        // return $data;
        return view('site.pages.message.index', $data);
    }

    public function showMessage(Request $request, $id)
    {
        $message = MessageReciever::with('message')->authUser($request->auth_user['id'])->find($id);
        if (!empty($message)) {
            $message->update([
                'status' => MessageReciever::MSG_STATUS['read'],
            ]);
        }
        $data['message'] = $message;

        $data['status'] = MessageReciever::MSG_STATUS;

        $data['title'] = trans('message_page.detail');
        return view('site.pages.message.detail', $data);
    }

    public function showSentItem(Request $request)
    {
        // $messages = MessageReciever::authUser($request->auth_user['id'])
        //     ->onlyInbox()->with([
        //         'message:id,sender_name,sender_email,subject,body'
        //     ])->orderBy('sended_at', 'DESC');
        $sentItems = Message::JoinRecievers()->AuthUser($request->auth_user['id'])->latest();

        $data['sentitems'] = $sentItems->paginate();

        $data['title'] = trans('layout.menu.message.child.sent');
        // return $data;
        return view('site.pages.message.sentitems', $data);
    }

    public function showDetailSentItem(Request $request, $id)
    {
        $sentItems = Message::with('recievers')->JoinRecievers()->AuthUser($request->auth_user['id'])->find($id);
        
        $data['message'] = $sentItems;
        $data['title'] = trans('message_page.detail');
        return view('site.pages.message.sentitems_detail', $data);
    }

    public function showComposeForm()
    {
        $data['title'] = trans('layout.menu.message.child.compose');
        return view('site.pages.message.compose', $data);
    }

    public function storeMessage(ComposeMessage $request)
    {
        DB::beginTransaction();
        try{
            $message = new Message($request->only('subject', 'body'));
            $message->fill([
                'user_id' => $request->auth_user['id'],
                'sender_name' => $request->auth_user['name'],
                'sender_email' => $request->auth_user['email'],
            ]);
            $message->save();

            $emails = [];
            $lists = explode(',', $request->input('recievers'));
            foreach ($lists as $value) {
                $emails[] = [
                    'email' => $value,
                    'status' => MessageReciever::MSG_STATUS['pending'],
                ];
            }
            $message->recievers()->createMany($emails);
            DB::commit();

            $request->session()->flash('flash_messages', ['success' => trans('messages.success.')]);
            return redirect()->route('sent-items');
        }catch(\Exception $e){
            DB::rollback();

            $request->session()->flash('flash_messages', ['errors' => trans('messages.errors.')]);
        }
        return redirect()->back()->withInput();
    }

    public function handleMessageAction(Request $request)
    {
        $this->validate($request, [
            'inboxes.*' => 'required',
            'action' => 'required|string|in:' . implode(',', $this->hanldeAction),
        ]);
        if (count($request->input('inboxes')) >= 1) {
            $executed = DB::transaction(function () use ($request) {
                $emails = MessageReciever::authUser($request->auth_user['id'])->whereIn('id', $request->input('inboxes'));

                switch ($request->input('action')) {
                    case 'trash':
                        return $emails->update([
                            'status' => MessageReciever::MSG_STATUS['trash']
                        ]);
                        break;
                    case 'unread':
                        return $emails->update([
                            'status' => MessageReciever::MSG_STATUS['read']
                        ]);
                        break;
                    case 'destroy':
                        return $emails->delete();
                        break;
                    default:
                        $request->session()->flash('flash_messages', [
                            'errors' => trans('messages.errors.inbox_action_notfound')
                        ]);
                        return false;
                        break;
                }
            });
            if ($executed) {
                $request->session()->flash('flash_messages', [
                    'success' => trans('messages.success.inbox.action.' . $request->input('action'))
                ]);
            }else{
                $request->session()->flash('flash_messages', [
                    'errors' => trans('messages.errors.inbox.action.' . $request->input('action'))
                ]);
            }
            return redirect()->route('inbox.index', [
                'type' => $request->input('action') == 'trash' ? 'trash' :  '',
            ]);
        }

        $request->session()->flash('flash_messages', [
            'errors' => trans('messages.errors.empty_selected_inbox')
        ]);
        return redirect()->back()->withInput();
    }
}

resources/views/site/pages/message/compose.blade.php
@extends('site.layouts.app')
@section('content')
    <div class="mail-container">
        @component('site.layouts.components.mail-header')
            @slot('title') {{ $title }} @endslot
        @endcomponent
        @includeWhen(session('flash_messages'), 'site.layouts.feedback')
        {{ Form::open([
            'route' => 'compose.store',
            'class' => 'new-mail-form form-horizontal'
        ]) }}
            <div class="row form-group {{ $errors->has('recievers') ? 'has-error simple' : '' }}">
                <label class="col-sm-2 control-label" for="mail-recievers">@lang('message_page.field.to')</label>
                <div class="col-sm-10 select2-primary">
                    <input id="mail-recievers" class="form-control" name="recievers" value="{{ old('recievers') }}" placeholder="{{ trans('message_page.field.to') }}">
                    {!! $errors->has("recievers") ? '<p class="help-block" data-id="mail-recievers">'.$errors->first('recievers').'</p>' : "" !!}
                </div>
            </div>
            <div class="row form-group {{ $errors->has('subject') ? 'has-error simple' : '' }}">
                <label class="col-sm-2 control-label" for="mail-subject">@lang('message_page.field.subject')</label>
                <div class="col-sm-10">
                    <input class="form-control" name="subject" id="mail-subject" value="{{ old('subject') }}" placeholder="{{ trans('message_page.field.subject') }}">
                    {!! $errors->has("subject") ? '<p class="help-block" data-id="mail-subject">'.$errors->first('subject').'</p>' : "" !!}
                </div>
            </div>
            <div class="row form-group {{ $errors->has('body') ? 'has-error simple' : '' }}">
                <div class="col-sm-offset-2 col-sm-10">
                    <textarea class="form-control" rows="5" name="body" id="mail-body" placeholder="{{ trans('message_page.field.body') }}">{!! old('body') !!}</textarea>
                    {!! $errors->has("body") ? '<p class="help-block" data-id="mail-body">'.$errors->first('body').'</p>' : "" !!}
                </div>
            </div>
            <div class="row form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">@lang('message_page.button.send')</button>
                </div>
            </div>
        {{ Form::close() }}
    </div>
@endsection
@push('scripts')
    <script type="text/javascript">
        window.initPixel.push(function(){
            $('#mail-recievers').select2({
                minimumInputLength: 3,
                tags:[],
                tokenSeparators: [",", " "]
            });

            $("#mail-body").summernote({
                height: 250,
                tabsize: 2,
            });
        });
    </script>
@endpush

resources/views/site/pages/message/detail.blade.php
@extends('site.layouts.app')
@section('content')
    <div class="mail-container">
        @includeWhen(session('flash_messages'), 'site.layouts.feedback')
        @component('site.layouts.components.mail-header') 
            @slot('title') {{ $message ? $message->message->subject : $title }} @endslot
            @if ($message)
                <span class="label label-primary">{{ $message->message_type_display }}</span>
            @endif
        @endcomponent
        @if (!empty($message))
            <div class="mail-controls clearfix">
                <div class="btn-toolbar wide-btns pull-left" role="toolbar">
                    <div class="btn-group">
                        <a href="{{ url()->previous() !== url()->current() ? url()->previous() : route('inbox.index') }}" class="btn"><i class="fa fa-chevron-left"></i></a>
                    </div>
                    <div class="btn-group">
                        {{ Form::open([
                            'method' => 'patch',
                            'route' => 'inbox.action'
                        ]) }}
                            <input type="hidden" name="inboxes[]" value="{{ $message->id }}">
                            <button type="submit" name="action" value="{{ $message->statys == $status['trash'] ? 'destroy' : 'trash' }}" class="btn"><i class="fa fa-trash-o"></i></button>
                        {{ Form::close() }}
                    </div>
                </div>
                @if ($message->status == $status['sended'] || $message->status == $status['read'])
                    <div class="btn-toolbar pull-right" role="toolbar">
                        <div class="btn-group">
                            <button type="button" class="btn btn-reply"><i class="fa fa-mail-reply"></i> @lang('message_page.button.reply')</button>
                        </div>
                    </div>
                @endif
            </div>
            <div class="mail-info">
                <div class="from">
                    <div class="name">{{ $message->message->sender_name }}</div>
                    <div class="email">{{ $message->message->sender_email }}</div>
                </div>
                <div class="date">{{ $message->sended_at }}</div>
            </div>
            <div class="mail-message-body" style="border-bottom: 1px solid #efefef;">
                {!! $message->message->body !!}
            </div>
            <div class="message-details-reply" style="margin-top: 16px;">
                @if ($message->status == $status['sended'] || $message->status == $status['read'])
                    <div id="message-details-reply" style="margin-top: 10px; {{ count($errors) == 0 ? 'display: none;' : '' }}">
                        {{ Form::open([
                            'route' => 'compose.store',
                            'class' => 'form-horizontal',
                        ]) }}
                            <div class="row form-group {{ $errors->has('recievers') ? 'has-error simple' : '' }}">
                                <label class="col-sm-2 control-label" for="mail-recievers">@lang('message_page.field.to')</label>
                                <div class="col-sm-10 select2-primary">
                                    <input id="mail-recievers" class="form-control" name="recievers" value="{{ old('recievers', $message->message->sender_email) }}" placeholder="{{ trans('message_page.field.to') }}">
                                    {!! $errors->has("recievers") ? '<p class="help-block" data-id="mail-recievers">'.$errors->first('recievers').'</p>' : "" !!}
                                </div>
                            </div>
                            <div class="row form-group {{ $errors->has('subject') ? 'has-error simple' : '' }}">
                                <label class="col-sm-2 control-label" for="mail-subject">@lang('message_page.field.subject')</label>
                                <div class="col-sm-10">
                                    <input class="form-control" name="subject" id="mail-subject" value="{{ old('subject', trans('message_page.reply_format', ['subject' => $message->message->subject])) }}" placeholder="{{ trans('message_page.field.subject') }}">
                                    {!! $errors->has("subject") ? '<p class="help-block" data-id="mail-subject">'.$errors->first('subject').'</p>' : "" !!}
                                </div>
                            </div>
                            <div class="row form-group {{ $errors->has('body') ? 'has-error simple' : '' }}">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <textarea class="form-control" rows="5" name="body" id="mail-body" placeholder="{{ trans('message_page.field.body') }}">{!! old('body') !!}</textarea>
                                    {!! $errors->has("body") ? '<p class="help-block" data-id="mail-body">'.$errors->first('body').'</p>' : "" !!}
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-primary">@lang('message_page.button.send')</button>
                                </div>
                            </div>
                        {{ Form::close() }}
                    </div>
                @endif
            </div>
        @else
            
        @endif
    </div>
@endsection
@push('scripts')
    <script type="text/javascript">
        window.initPixel.push(function(){
            $('.btn-reply').click(function(){
                // console.log($(this));
                $('#message-details-reply').slideToggle();
            });

            $('#mail-recievers').select2({
                minimumInputLength: 3,
                tags:[],
                tokenSeparators: [",", " "]
            });

            $('#message-details-reply textarea').summernote({
                height: 200,
                tabsize: 2
            });
        });
    </script>
@endpush

resources/views/site/pages/message/index.blade.php
@extends('site.layouts.app')
@section('content')
    @includeWhen(session('flash_messages'), 'site.layouts.feedback')
    <div class="mail-container">
        @component('site.layouts.components.mail-header') 
            @slot('title') {{ $title }} @endslot
            {{ Form::open(['class' => 'pull-right', 'style' => 'width: 200px; margin-top: 3px;']) }}
                <div class="form-group input-group-sm has-feedback no-margin">
                    <input id="keyword" type="text" name="keyword" placeholder="{{ trans('message_page.field.search') }}" class="form-control">
                    <span class="fa fa-search form-control-feedback" style="top: -1px"></span>
                </div>
            {{ Form::close() }}
        @endcomponent
        {{ Form::open([
            'method' => 'patch',
            'route' => 'inbox.action',
        ]) }}
            <div class="mail-controls clearfix">
                <div class="btn-toolbar wide-btns pull-left" role="toolbar">
                    <div class="btn-group">
                        <div class="btn-group">
                            <button type="button" class="btn dropdown-toggle" data-toggle="dropdown"><i class="fa fa-check-square-o"></i>&nbsp;<i class="fa fa-caret-down"></i></button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">@lang('message_page.text.check.all')</a></li>
                                <li><a href="#">@lang('message_page.text.check.unread')</a></li>
                                <li class="divider"></li>
                                <li><a href="#">@lang('message_page.text.uncheck.all')</a></li>
                                <li><a href="#">@lang('message_page.text.uncheck.unread')</a></li>
                            </ul>
                        </div>
                        <a href="{{ route(Route::currentRouteName()) }}" class="btn"><i class="fa fa-repeat"></i></a>
                    </div>
                    <div class="btn-group">
                        <button name="action" value="{{ $trash_action }}" type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
                    </div>
                </div>
                {!! $inboxes->links('site.pages.message.pagination') !!}
                <div class="pages pull-right">
                    {{ trans('message_page.pagination_status', [
                        'from' => $inboxes->currentPage() > 1 
                                ? ($inboxes->currentPage() - 1) * $inboxes->perPage() + 1
                                : 1,
                        'to' => $inboxes->currentPage() > 1 
                                ? (($inboxes->currentPage() - 1) * $inboxes->perPage()) + $inboxes->count() 
                                : $inboxes->count(),
                        'total' => $inboxes->total(),
                    ]) }}
                </div>
            </div>
            <ul class="mail-list">
                @forelse ($inboxes as $inbox)
                    <li class="mail-item {{ $inbox->is_unread ? 'unread' : '' }}">
                        <div class="m-chck">
                            <label class="px-single">
                                <input type="checkbox" name="inboxes[]" value="{{ $inbox->id }}" class="px {{ $inbox->is_unread ? 'unread' : 'read' }}" {{ in_array($inbox->id, old('inboxes', [])) ? 'checked' : '' }}>
                                <span class="lbl"></span>
                            </label>
                        </div>
                        {{-- <div class="m-star"><a href="#"></a></div> --}}
                        <div class="m-from"><a href="{{ route('inbox.detail', ['id' => $inbox->id]) }}">{{ $inbox->message->sender_name }}</a></div>
                        <div class="m-subject">
                            {!! $inbox->is_unread ? '<span class="label label-info">' . trans('message_page.new') . '</span>' : '' !!}
                            &nbsp;&nbsp;
                            <a href="{{ route('inbox.detail', ['id' => $inbox->id]) }}">{{ $inbox->message->subject }}</a>
                        </div>
                        <div class="m-date">{{ $inbox->sended_at->diffForHumans() }}</div>
                    </li>
                @empty
                    <li class="mail-item">
                        <div class="text-center">Tidak ada pesan.</div>
                    </li>
                @endforelse
            </ul>
        {{ Form::close() }}
    </div>
@endsection

resources/views/site/pages/message/pagination.blade.php
@if ($paginator->hasPages())
    <div class="btn-toolbar pull-right" role="toolbar">
        <div class="btn-group">
            {{-- Previous Page Link --}}
            @if ($paginator->onFirstPage())
                <button type="button" class="btn" disabled>
                    <i class="fa fa-chevron-left"></i>
                </button>
            @else
                <a href="{{ $paginator->previousPageUrl() }}" class="btn" rel="prev"><i class="fa fa-chevron-left"></i></a>
            @endif

            {{-- Next Page Link --}}
            @if ($paginator->hasMorePages())
                <a href="{{ $paginator->nextPageUrl() }}" class="btn" rel="prev"><i class="fa fa-chevron-right"></i></a>
            @else
                <button type="button" class="btn" disabled>
                    <i class="fa fa-chevron-right"></i>
                </button>
            @endif
        </div>
    </div>
@endif

resources/views/site/pages/message/sentitems.blade.php
@extends('site.layouts.app')
@section('content')
    @includeWhen(session('flash_messages'), 'site.layouts.feedback')
    <div class="mail-container">
        @component('site.layouts.components.mail-header') 
            @slot('title') {{ $title }} @endslot
            {{ Form::open(['route' => 'sent-items', 'method' => 'GET', 'class' => 'pull-right', 'style' => 'width: 200px; margin-top: 3px;']) }}
                <div class="form-group input-group-sm has-feedback no-margin">
                    <input id="keyword" type="text" name="keyword" placeholder="{{ trans('message_page.field.search') }}" class="form-control">
                    <span class="fa fa-search form-control-feedback" style="top: -1px"></span>
                </div>
            {{ Form::close() }}
        @endcomponent
        {{ Form::open([
            'method' => 'patch',
            'route' => 'inbox.action',
        ]) }}
            <ul class="mail-list">
                @forelse ($sentitems as $item)
                    <li class="mail-item">
                        <div class="m-chck">
                            <label class="px-single">
                                <input type="checkbox" name="inboxes[]" value="{{ $item->id }}" class="px" {{ in_array($item->id, old('items', [])) ? 'checked' : '' }}>
                                <span class="lbl"></span>
                            </label>
                        </div>
                        {{-- <div class="m-star"><a href="#"></a></div> --}}
                        <div class="m-from">
                            <a href="{{ route('sent-items.detail', ['id' => $item->id]) }}"><span style="text-overflow: ellipsis;">{{ $item->all_recievers }}</span></a>
                        </div>
                        <div class="m-subject">
                            <a href="{{ route('sent-items.detail', ['id' => $item->id]) }}">{{ $item->subject }}</a>
                        </div>
                        <div class="m-date">{{ $item->created_at->diffForHumans() }}</div>
                    </li>
                @empty
                    <li class="mail-item">
                        <div class="text-center">Tidak ada pesan.</div>
                    </li>
                @endforelse
            </ul>
        {{ Form::close() }}
    </div>
@endsection

resources/views/site/pages/message/sentitems_detail.blade.php
@extends('site.layouts.app')
@section('content')
    <div class="mail-container">
        @includeWhen(session('flash_messages'), 'site.layouts.feedback')
        @component('site.layouts.components.mail-header') 
            @slot('title') {{ $message ? $message->subject : $title }} @endslot
        @endcomponent
        @if (!empty($message))
            <div class="mail-controls clearfix">
                <div class="btn-toolbar wide-btns pull-left" role="toolbar">
                    <div class="btn-group">
                        <a href="{{ url()->previous() !== url()->current() ? url()->previous() : route('sent-items') }}" class="btn"><i class="fa fa-chevron-left"></i></a>
                    </div>
                    {{-- <div class="btn-group">
                        {{ Form::open([
                            'method' => 'patch',
                            'route' => 'inbox.action'
                        ]) }}
                            <input type="hidden" name="inboxes[]" value="{{ $message->id }}">
                            <button type="submit" name="action" value="{{ $message->statys == $status['trash'] ? 'destroy' : 'trash' }}" class="btn"><i class="fa fa-trash-o"></i></button>
                        {{ Form::close() }}
                    </div> --}}
                </div>
            </div>
            <div class="mail-info">
                {{ $message->all_recievers }}
            </div>
            <div class="mail-info">
                <div class="from">
                    <div class="name">{{ $message->sender_name }}</div>
                    <div class="email">{{ $message->sender_email }}</div>
                </div>
                <div class="date">{{ $message->created_at }}</div>
            </div>
            <div class="mail-message-body" style="border-bottom: 1px solid #efefef;">
                {!! $message->body !!}
            </div>        
        @endif
    </div>
@endsection